Repository dstl/Stone-Soup, pull requests merged in 2020-12, with the labels that each got.

#345 Fix SIAP metric component _nu_j
  stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
  stonesoup/metricgenerator/tracktotruthmetrics.py
Labels: bug

#346 Modify gaussian models to raise errors with None covariances
  stonesoup/models/base.py
  stonesoup/models/measurement/tests/test_combined.py
  stonesoup/models/measurement/tests/test_models.py
  stonesoup/models/transition/tests/test_time_invariant.py
Labels: bug

#348 Fix issue with version, effecting pip install with Read The Docs
  setup.py
  stonesoup/__init__.py
Labels: bug

#338 Add plotting class and update tutorials
  docs/source/doc_extensions.py
  docs/source/stonesoup.plotter.rst
  docs/source/stonesoup.rst
  docs/tutorials/01_KalmanFilterTutorial.py
  docs/tutorials/02_ExtendedKalmanFilterTutorial.py
  docs/tutorials/03_UnscentedKalmanFilterTutorial.py
  docs/tutorials/04_ParticleFilter.py
  docs/tutorials/05_DataAssociation-Clutter.py
  docs/tutorials/06_DataAssociation-MultiTargetTutorial.py
  docs/tutorials/07_PDATutorial.py
  docs/tutorials/08_JPDATutorial.py
  docs/tutorials/09_Initiators_&_Deleters.py
  stonesoup/plotter.py
Labels: enhancement

#342 Modify metric manager add_data method to have separate kwargs
  docs/examples/Metrics.py
  stonesoup/metricgenerator/manager.py
  stonesoup/metricgenerator/tests/test_basicmetrics.py
  stonesoup/metricgenerator/tests/test_manager.py
  stonesoup/metricgenerator/tests/test_ospametric.py
Labels: breaking, bug

#328 Modify tracks to store metadata history
  stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
  stonesoup/types/tests/test_track.py
  stonesoup/types/track.py
Labels: enhancement

#350 Remove tutorial pyplot imports and fix flake8 errors
  docs/tutorials/01_KalmanFilterTutorial.py
  docs/tutorials/02_ExtendedKalmanFilterTutorial.py
  docs/tutorials/03_UnscentedKalmanFilterTutorial.py
  docs/tutorials/04_ParticleFilter.py
  docs/tutorials/05_DataAssociation-Clutter.py
  docs/tutorials/08_JPDATutorial.py
  docs/tutorials/09_Initiators_&_Deleters.py
  docs/tutorials/10_Simulation_&_Tracking_Components.py
Labels: documentation
