Repository dstl/Stone-Soup, pull requests merged in 2021-02, with the labels that each got.

#362 Close figures when finished processing file in Sphinx Gallery
  docs/source/doc_extensions.py
Labels: documentation

#361 AESA Radar and Beam Shape beam power method argument changes
  stonesoup/sensor/radar/beam_pattern.py
  stonesoup/sensor/radar/beam_shape.py
  stonesoup/sensor/radar/radar.py
  stonesoup/sensor/radar/tests/test_beam_shape.py
  stonesoup/sensor/radar/tests/test_radar.py
Labels: breaking, bug

#278 Orbitalstate
  docs/source/stonesoup.functions.rst
  docs/source/stonesoup.types.rst
  stonesoup/functions.py
  stonesoup/orbital_functions.py
  stonesoup/tests/test_functions.py
  stonesoup/tests/test_orbital_functions.py
  stonesoup/types/angle.py
  stonesoup/types/orbitalstate.py
  stonesoup/types/tests/test_orbital.py
Labels: enhancement

#368 Data Associator Class modifications
  stonesoup/dataassociator/base.py
  stonesoup/dataassociator/neighbour.py
  stonesoup/dataassociator/probability.py
  stonesoup/hypothesiser/base.py
  stonesoup/tracker/tests/conftest.py
Labels: breaking

#370 Update Contributing documentation
  docs/source/contributing.rst
Labels: documentation

#373 Fix animation control layout in Sphinx-Gallery examples
  docs/source/_static/css/custom.css
Labels: documentation

#372 Minor edits for 01 Tutorial
  docs/tutorials/01_KalmanFilterTutorial.py
Labels: documentation

#374 Adding link to TransitionModel in the Prediction
  stonesoup/predictor/kalman.py
  stonesoup/predictor/particle.py
  stonesoup/predictor/tests/test_kalman.py
  stonesoup/types/prediction.py
Labels: enhancement

#366 Add ID based associator
  stonesoup/dataassociator/tests/test_tracktotrack.py
  stonesoup/dataassociator/tracktotrack.py
Labels: enhancement

#375 Add support for plugins
  docs/source/stonesoup.plugins.rst
  docs/source/stonesoup.rst
  stonesoup/plugins.py
Labels: enhancement

#380 Fix Edit on GitHub links on documentation.
  docs/source/_templates/breadcrumbs.html
Labels: documentation

#365 Vectorise particle filter
  docs/tutorials/04_ParticleFilter.py
  stonesoup/models/base.py
  stonesoup/models/measurement/nonlinear.py
  stonesoup/models/measurement/tests/test_models.py
  stonesoup/plotter.py
  stonesoup/predictor/particle.py
  stonesoup/resampler/particle.py
  stonesoup/types/array.py
  stonesoup/types/numeric.py
  stonesoup/types/particle.py
  stonesoup/types/state.py
  stonesoup/types/tests/test_particle.py
  stonesoup/updater/particle.py
Labels: breaking, enhancement

#381 SIAP text
  stonesoup/metricgenerator/tracktotruthmetrics.py
Labels: documentation

#132 Add Gromov Particle Flow Updater
  docs/examples/ParticleFlow.py
  docs/source/conf.py
  stonesoup/functions/__init__.py
  stonesoup/functions/tests/test_functions.py
  stonesoup/initiator/simple.py
  stonesoup/initiator/tests/test_simple.py
  stonesoup/predictor/particle.py
  stonesoup/predictor/tests/test_particle.py
  stonesoup/types/state.py
  stonesoup/types/tests/test_state.py
  stonesoup/updater/particle.py
  stonesoup/updater/tests/test_particle.py
Labels: enhancement

#384 Change time-based SIAP titles
  docs/examples/Metrics.py
  stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
  stonesoup/metricgenerator/tracktotruthmetrics.py
Labels: documentation

#383 Various test fixes for print statements, floating point errors and divide by zero warnings
  stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
  stonesoup/models/measurement/tests/test_models.py
  stonesoup/resampler/particle.py
  stonesoup/updater/tests/test_pointprocess.py
Labels: bug

#385 Fix Particle Flow example due to metric name change
  docs/examples/ParticleFlow.py
Labels: documentation

#382 Fix plotter metric so it uses Stone Soup Plotter class
  docs/examples/Metrics.py
  docs/source/stonesoup.metricgenerator.plotter.rst
  docs/source/stonesoup.metricgenerator.rst
  docs/tutorials/10_Simulation_&_Tracking_Components.py
  stonesoup/metricgenerator/plotter.py
  stonesoup/simulator/simple.py
Labels: enhancement

#378 Kalman smoother
  docs/source/interface.rst
  docs/source/stonesoup.rst
  docs/source/stonesoup.smoother.rst
  stonesoup/smoother/base.py
  stonesoup/smoother/kalman.py
  stonesoup/smoother/lineargaussian.py
  stonesoup/smoother/tests/test_kalman.py
  stonesoup/smoother/tests/test_lineargaussian.py
Labels: breaking

#389 Increase tolerance on particle updater test
  stonesoup/updater/tests/test_particle.py
Labels: tests

#390 Handle warning raised on 2D plotter metric test
  stonesoup/metricgenerator/tests/test_plotter.py
Labels: tests

#391 Fix Measures to work with tuple mapping type
  stonesoup/measures.py
  stonesoup/tests/test_measures.py
Labels: bug

#393 Fix CartesianToBearingRange inverse_function for 3D state space.
  stonesoup/models/measurement/nonlinear.py
  stonesoup/models/measurement/tests/test_models.py
Labels: bug
