Repository dstl/Stone-Soup, pull requests merged in 2021-01, with the labels that each got.

#352 Modify ID SIAPs to consider track metadata at timestamps
  stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
  stonesoup/metricgenerator/tracktotruthmetrics.py
Labels: enhancement

#318 Add closed continuous (real) interval type
  docs/source/stonesoup.types.rst
  stonesoup/types/interval.py
  stonesoup/types/tests/test_interval.py
Labels: enhancement

#355 Add Uncertainty Metric
  docs/source/stonesoup.metricgenerator.rst
  docs/source/stonesoup.metricgenerator.uncertaintymetric.rst
  stonesoup/metricgenerator/ospametric.py
  stonesoup/metricgenerator/tests/test_uncertaintymetric.py
  stonesoup/metricgenerator/uncertaintymetric.py
Labels: enhancement

#357 Add Binder support for notebooks hosted on Read the Docs
  README.md
  binder/postBuild
  docs/source/conf.py
  docs/source/requirements.txt
Labels: documentation

#331 Add TensorNets based detector and modify FFmpeg Reader
  docs/source/conf.py
  docs/source/stonesoup.detector.rst
  setup.py
  stonesoup/detector/_video.py
  stonesoup/detector/tensorflow.py
  stonesoup/detector/tensornets.py
  stonesoup/reader/video.py
Labels: enhancement

#360 Add abstractmethod decorator to Radar Beam Pattern/Shape
  stonesoup/sensor/radar/beam_pattern.py
  stonesoup/sensor/radar/beam_shape.py
  stonesoup/sensor/radar/tests/test_beam_pattern.py
  stonesoup/sensor/radar/tests/test_beam_shape.py
Labels: bug

#246 Range velocity binning
  docs/examples/range_range_rate_binning.py
  stonesoup/models/measurement/nonlinear.py
  stonesoup/models/measurement/tests/test_models.py
Labels: enhancement
