Repository dstl/Stone-Soup, pull requests merged in 2021-08, with the labels that each got.

#455 Add tutorial on the GMPHD filter in Stone Soup
  docs/tutorials/11_GMPHDTutorial.py
Labels: documentation

#482 Fix multi-transition platform loop
  stonesoup/movable/movable.py
Labels: bug

#483 Remove unnecessary additional noise in radar fov check
  stonesoup/sensor/radar/radar.py
Labels: bug

#491 Vectorise Jacobian calculation
  stonesoup/functions/__init__.py
  stonesoup/functions/tests/test_functions.py
Labels: enhancement
