Repository dstl/Stone-Soup, pull requests merged in 2021-12, with the labels that each got.

#549 Improve readability and limit size of repr output
  stonesoup/base.py
  stonesoup/tests/test_repr.py
Labels: enhancement

#543 Add method to copy prior state properties of a platform across to a new state
  stonesoup/movable/movable.py
  stonesoup/movable/tests/test_movable.py
  stonesoup/types/prediction.py
  stonesoup/types/state.py
  stonesoup/types/tests/test_state.py
  stonesoup/types/update.py
  stonesoup/updater/particle.py
Labels: breaking

#563 Introduce resampler that checks if resampling required
  stonesoup/resampler/particle.py
  stonesoup/resampler/tests/test_particle.py
Labels: enhancement

#505 Add SIAP alternative generator
  docs/examples/Metrics.py
  docs/examples/ParticleFlow.py
  stonesoup/metricgenerator/metrictables.py
  stonesoup/metricgenerator/tests/conftest.py
  stonesoup/metricgenerator/tests/test_tables.py
  stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
  stonesoup/metricgenerator/tracktotruthmetrics.py
Labels: enhancement

#565 Fix IDSIAP docstring bullet list error
  stonesoup/metricgenerator/tracktotruthmetrics.py
Labels: bug
