Repository dstl/Stone-Soup, pull requests merged in 2021-04, with the labels that each got.

#429 Add mapping to Combined Measurement Model
  stonesoup/models/measurement/nonlinear.py
  stonesoup/models/measurement/tests/test_combined.py
Labels: bug

#430 Plotter group measurements/clutter into single plot call
  stonesoup/plotter.py
Labels: enhancement

#398 Alpha-Beta updater
  docs/source/stonesoup.updater.rst
  stonesoup/updater/alphabeta.py
  stonesoup/updater/base.py
  stonesoup/updater/kalman.py
  stonesoup/updater/tests/test_alphabeta.py
Labels: enhancement

#431 Speed up track to truth associator by avoiding searching of all times
  stonesoup/dataassociator/tracktotrack.py
  stonesoup/types/state.py
  stonesoup/types/tests/test_state.py
Labels: enhancement

#120 Create OpenSky Network REST API Reader
  docs/source/stonesoup.reader.rst
  setup.py
  stonesoup/reader/opensky.py
  stonesoup/reader/tests/test_opensky.py
Labels: enhancement

#434 Add DOI badge to README
  README.md
Labels: documentation

#437 Fixing timestamps for the video reader
  stonesoup/reader/video.py
Labels: bug
