Repository dstl/Stone-Soup, pull requests merged in 2021-06, with the labels that each got.

#447 Fix Weighted Gaussian Prediction to inherit from correct parent
  stonesoup/types/prediction.py
Labels: bug

#145 Add tree data structures for gating
  docs/source/stonesoup.dataassociator.rst
  setup.py
  stonesoup/dataassociator/base.py
  stonesoup/dataassociator/neighbour.py
  stonesoup/dataassociator/probability.py
  stonesoup/dataassociator/tests/conftest.py
  stonesoup/dataassociator/tests/test_neighbour.py
  stonesoup/dataassociator/tests/test_probability.py
  stonesoup/dataassociator/tests/test_tree.py
  stonesoup/dataassociator/tree.py
Labels: enhancement

#449 Fixed an error in the angle calculations in smooth transition model maker
  stonesoup/simulator/transition.py
Labels: bug

#450 Add note about using mixture tracker for (J)PDA in final tutorial
  docs/tutorials/07_PDATutorial.py
  docs/tutorials/10_Simulation_&_Tracking_Components.py
Labels: documentation
