Repository dstl/Stone-Soup, pull requests merged in 2021-03, with the labels that each got.

#395 Update copyright/license year.
  LICENSE
  docs/source/conf.py
  stonesoup/__init__.py
Labels: documentation

#405 Modify AssociationSet types to have a set-like interface
  stonesoup/types/association.py
  stonesoup/types/tests/test_association.py
Labels: enhancement

#407 Ensure registered subclasses are in parent subclasses list
  stonesoup/base.py
  stonesoup/types/tests/test_state.py
Labels: bug

#406 Include timestamp with Initiator and allow predictions with multi measurement initiator
  docs/demos/UAV_tutorial.py
  docs/examples/Sensor_Platform_Simulation.py
  docs/tutorials/09_Initiators_&_Deleters.py
  stonesoup/initiator/base.py
  stonesoup/initiator/simple.py
  stonesoup/initiator/tests/test_simple.py
  stonesoup/initiator/tests/test_wrapper.py
  stonesoup/tracker/simple.py
  stonesoup/tracker/tests/conftest.py
Labels: breaking

#408 Sensor and platform minor documentation changes
  docs/source/stonesoup.rst
  stonesoup/platform/base.py
  stonesoup/sensor/base.py
  stonesoup/sensor/passive.py
  stonesoup/sensor/radar/radar.py
Labels: documentation

#410 Add deleter and initiator base class type hints and minor doc changes
  stonesoup/deleter/base.py
  stonesoup/deleter/error.py
  stonesoup/deleter/multi.py
  stonesoup/initiator/base.py
  stonesoup/initiator/simple.py
Labels: documentation

#412 Add type hints and update documentation on Models
  .coveragerc
  stonesoup/models/base.py
  stonesoup/models/control/base.py
  stonesoup/models/measurement/base.py
  stonesoup/models/transition/base.py
  stonesoup/platform/base.py
Labels: documentation

#413 Add type annotations to base classes, and shorten type hints in documentation
  docs/source/doc_extensions.py
  stonesoup/base.py
  stonesoup/models/measurement/nonlinear.py
  stonesoup/reader/video.py
  stonesoup/types/orbitalstate.py
Labels: documentation

#409 Add DataAssociator and Hypothesiser type hints, and passthrough kwargs
  stonesoup/dataassociator/base.py
  stonesoup/dataassociator/neighbour.py
  stonesoup/dataassociator/probability.py
  stonesoup/hypothesiser/base.py
  stonesoup/hypothesiser/distance.py
  stonesoup/hypothesiser/gaussianmixture.py
  stonesoup/hypothesiser/probability.py
Labels: documentation

#422 Match colours of ellipses, and fix mappings with track uncertainty in Plotter
  stonesoup/plotter.py
Labels: bug

#417 Add option to delete posterior predictions from deleted tracks
  docs/demos/AIS_Solent_Tracker.py
  docs/tutorials/09_Initiators_&_Deleters.py
  docs/tutorials/10_Simulation_&_Tracking_Components.py
  stonesoup/deleter/base.py
  stonesoup/deleter/tests/test_base.py
  stonesoup/deleter/tests/test_error.py
  stonesoup/deleter/tests/test_multi.py
  stonesoup/deleter/tests/test_time.py
Labels: breaking, enhancement

#416 Add mapping to CovarianceBasedDeleter
  stonesoup/deleter/error.py
  stonesoup/deleter/tests/test_error.py
Labels: enhancement

#426 Fix gm_reduce_single.
  stonesoup/functions/__init__.py
  stonesoup/functions/tests/test_functions.py
Labels: bug
