Repository dstl/Stone-Soup, pull requests merged in 2022-06, with the labels that each got.

#644 Modify EnsembleState to use StateVectors
  stonesoup/predictor/ensemble.py
  stonesoup/predictor/tests/test_ensemble.py
  stonesoup/types/state.py
  stonesoup/types/tests/test_state.py
  stonesoup/updater/ensemble.py
Labels: enhancement

#654 Correct spelling mistakes, typos and links.
  docs/demos/UAV_tutorial.py
  docs/demos/Video_Processing.py
  docs/examples/Classifying_Using_HMM.py
  docs/examples/Creating_Actionable_Sensor.py
  docs/examples/Disjoint_Tracking_Classification.py
  docs/examples/MTT_3D_Platform.py
  docs/examples/Sensor_Platform_Simulation.py
  docs/examples/Smooth_Platform_Coordinate_Transitions.py
  docs/examples/range_range_rate_binning.py
  docs/source/auto_demos/Video_Processing.ipynb
  docs/source/auto_demos/Video_Processing.py.md5
  docs/source/auto_demos/Video_Processing.rst
  docs/tutorials/05_DataAssociation-Clutter.py
  docs/tutorials/06_DataAssociation-MultiTargetTutorial.py
  docs/tutorials/08_JPDATutorial.py
  docs/tutorials/11_GMPHDTutorial.py
Labels: documentation

#660 Fix incorrect arguments in particle predictor
  stonesoup/predictor/particle.py
Labels: bug

#659 Add Sensor Management Tutorials
  docs/source/_static/SM_flow_diagram.png
  docs/tutorials/sensormanagement/01_SingleSensorManagement.py
  docs/tutorials/sensormanagement/02_MultiSensorManagement.py
  docs/tutorials/sensormanagement/README.rst
  stonesoup/plotter.py
  stonesoup/sensormanager/tests/test_sensormanager.py
  stonesoup/tests/test_plotter.py
Labels: documentation
