Repository dstl/Stone-Soup, pull requests merged in 2022-02, with the labels that each got.

#586 Enable Kalman Smoother to work with multi-hypothesis states
  stonesoup/smoother/kalman.py
  stonesoup/smoother/tests/test_kalman.py
Labels: bug

#596 Fix a bug in Tutorial 09
  docs/tutorials/09_Initiators_&_Deleters.py
Labels: documentation

#506 Add nonlinear constant turn models. Update transition model class hierarchy
  docs/demos/OpenSky_Demo.py
  docs/examples/Moving_Platform_Simulation.py
  docs/examples/Smooth_Platform_Coordinate_Transitions.py
  stonesoup/initiator/simple.py
  stonesoup/initiator/tests/test_simple.py
  stonesoup/models/base.py
  stonesoup/models/measurement/nonlinear.py
  stonesoup/models/transition/base.py
  stonesoup/models/transition/linear.py
  stonesoup/models/transition/nonlinear.py
  stonesoup/models/transition/tests/conftest.py
  stonesoup/models/transition/tests/test_ca.py
  stonesoup/models/transition/tests/test_combined.py
  stonesoup/models/transition/tests/test_ct.py
  stonesoup/models/transition/tests/test_cts.py
  stonesoup/models/transition/tests/test_nlct.py
  stonesoup/models/transition/tests/test_nlcts.py
  stonesoup/models/transition/tests/test_singer.py
  stonesoup/models/transition/tests/test_singer_approximate.py
  stonesoup/movable/tests/test_movable.py
  stonesoup/platform/tests/test_platform_base.py
  stonesoup/plotter.py
  stonesoup/simulator/transition.py
  stonesoup/types/tests/test_array.py
Labels: breaking

#589 Make measurement model optional in measurement-based initiators
  stonesoup/initiator/simple.py
  stonesoup/initiator/tests/test_simple.py
Labels: breaking

#600 Fix linear measurement model tests
  stonesoup/models/measurement/tests/test_lg.py
Labels: tests

#415 Trackers are Iterables instead of Generators
  docs/demos/AIS_Solent_Tracker.py
  docs/demos/OpenSky_Demo.py
  docs/examples/Metrics.py
  docs/examples/Sensor_Platform_Simulation.py
  stonesoup/reader/yaml.py
  stonesoup/tracker/base.py
  stonesoup/tracker/pointprocess.py
  stonesoup/tracker/simple.py
  stonesoup/writer/tests/conftest.py
Labels: breaking
