Repository dstl/Stone-Soup, pull requests merged in 2022-07, with the labels that each got.

#670 Add Image Readers to documentation
  docs/source/stonesoup.reader.rst
Labels: documentation

#669 Ensemble Square Root Updater
  stonesoup/models/base.py
  stonesoup/models/measurement/linear.py
  stonesoup/models/measurement/nonlinear.py
  stonesoup/models/transition/nonlinear.py
  stonesoup/predictor/particle.py
  stonesoup/updater/ensemble.py
  stonesoup/updater/particle.py
  stonesoup/updater/tests/test_ensemble.py
Labels: enhancement

#672 Fix plotting of track state in moving platform example
  docs/examples/Moving_Platform_Simulation.py
Labels: documentation

#662 Fix tree data associators to work with particle states
  stonesoup/dataassociator/tests/test_tree.py
  stonesoup/dataassociator/tree.py
Labels: bug

#661 Add additional functionality into Plotter class.
  stonesoup/plotter.py
  stonesoup/tests/test_plotter.py
Labels: enhancement

#649 Add parameter to limit number of components in GaussianMixtureReducer
  docs/tutorials/11_GMPHDTutorial.py
  stonesoup/mixturereducer/gaussianmixture.py
  stonesoup/mixturereducer/tests/test_gaussian_mixture_reducer.py
Labels: bug, enhancement

#678 Add optional kDTree to Gaussian Mixture Reducer merge step
  stonesoup/mixturereducer/gaussianmixture.py
  stonesoup/mixturereducer/tests/test_gaussian_mixture_reducer.py
Labels: enhancement

#676 Enable use of kDTree with Gaussian Mixture Hypothesiser
  stonesoup/dataassociator/tests/test_tree.py
  stonesoup/dataassociator/tree.py
  stonesoup/hypothesiser/gaussianmixture.py
  stonesoup/hypothesiser/tests/test_gaussianmixture.py
Labels: enhancement

#680 Remove `hasattr` in Measures to avoid calling `mean` twice
  stonesoup/measures.py
Labels: bug

#681 Add ChernoffUpdater class and track feeder
  docs/source/stonesoup.feeder.rst
  docs/source/stonesoup.updater.rst
  stonesoup/feeder/tests/test_track.py
  stonesoup/feeder/track.py
  stonesoup/updater/chernoff.py
  stonesoup/updater/tests/test_chernoff.py
Labels: enhancement
