Repository dstl/Stone-Soup, pull requests merged in 2022-09, with the labels that each got.

#709 Modify assign2D to exploit NumPy indexing
  stonesoup/dataassociator/_assignment.py
  stonesoup/dataassociator/neighbour.py
Labels: enhancement

#711 Standardise clearable cached properties on Stone Soup Base/Property
  stonesoup/_util.py
  stonesoup/base.py
  stonesoup/models/measurement/nonlinear.py
  stonesoup/types/state.py
  stonesoup/types/tests/test_state.py
Labels: breaking

#710 Reduce redundant calls to mod_angle method in Angle type
  stonesoup/types/angle.py
Labels: enhancement

#712 Pre-fetch noise values for sensor measure method
  stonesoup/sensor/passive.py
  stonesoup/sensor/radar/radar.py
Labels: enhancement

#714 Improve logic of readonly property checking to avoid double settting
  stonesoup/base.py
Labels: bug

#720 Fix mapping in TPR tree causing error when mapping is tuple
  stonesoup/dataassociator/tree.py
Labels: bug

#721 Fix plotting error when a track only has a single state
  stonesoup/plotter.py
Labels: bug

#725 Adding tests for the copying of tracks
  stonesoup/types/tests/test_track.py
Labels: tests

#458 Add 2d density plot to Plotter
  docs/examples/density_plot_example.py
  stonesoup/plotter.py
  stonesoup/tests/test_plotter.py
Labels: enhancement
