Repository dstl/Stone-Soup, pull requests merged in 2022-01, with the labels that each got.

#504 Add hidden Markov model implementation for classification
  docs/examples/Classifying_Using_HMM.py
  docs/source/stonesoup.hypothesiser.rst
  docs/source/stonesoup.initiator.rst
  docs/source/stonesoup.models.measurement.rst
  docs/source/stonesoup.models.transition.rst
  docs/source/stonesoup.predictor.rst
  docs/source/stonesoup.sensor.rst
  docs/source/stonesoup.updater.rst
  stonesoup/dataassociator/neighbour.py
  stonesoup/hypothesiser/categorical.py
  stonesoup/hypothesiser/tests/conftest.py
  stonesoup/hypothesiser/tests/test_categorical.py
  stonesoup/initiator/categorical.py
  stonesoup/initiator/tests/test_categorical.py
  stonesoup/measures.py
  stonesoup/models/measurement/categorical.py
  stonesoup/models/measurement/tests/test_categorical.py
  stonesoup/models/transition/categorical.py
  stonesoup/models/transition/tests/test_categorical.py
  stonesoup/predictor/categorical.py
  stonesoup/predictor/tests/test_categorical.py
  stonesoup/sensor/categorical.py
  stonesoup/sensor/tests/test_categorical.py
  stonesoup/tests/test_measures.py
  stonesoup/types/detection.py
  stonesoup/types/groundtruth.py
  stonesoup/types/hypothesis.py
  stonesoup/types/prediction.py
  stonesoup/types/state.py
  stonesoup/types/tests/test_state.py
  stonesoup/types/update.py
  stonesoup/updater/categorical.py
  stonesoup/updater/tests/test_categorical.py
Labels: enhancement

#569 Drop Python 3.6 support
  .circleci/config.yml
  .codecov.yml
  README.md
  setup.py
  stonesoup/base.py
Labels: breaking

#570 Return metrics in a dictionary
  docs/examples/Metrics.py
  docs/examples/ParticleFlow.py
  stonesoup/metricgenerator/manager.py
  stonesoup/metricgenerator/tests/test_basicmetrics.py
  stonesoup/metricgenerator/tests/test_manager.py
Labels: breaking

#573 Fix probability hypothesis equality check
  stonesoup/types/hypothesis.py
  stonesoup/types/tests/test_hypothesis.py
Labels: bug
