Repository dstl/Stone-Soup, pull requests merged in 2022-04, with the labels that each got.

#619 Fix SIAP ID Correctness Division Error
  stonesoup/metricgenerator/tracktotruthmetrics.py
Labels: bug

#621 Add sensor suite type
  stonesoup/sensor/sensor.py
  stonesoup/sensor/tests/test_sensor.py
Labels: enhancement

#626 Update CircleCI artifacts redirector
  .github/workflows/docs-link.yml
Labels: tests
