Repository dstl/Stone-Soup, pull requests merged in 2022-10, with the labels that each got.

#724 Fix bug with pre-fetching noise in cases of only a single target
  stonesoup/sensor/passive.py
  stonesoup/sensor/radar/radar.py
Labels: bug

#735 Disable documentation table of content entries for objects
  docs/source/conf.py
Labels: documentation

#738 Fixed TypeError being thrown on certain Gaussian states in the Plotter.plot_tracks function
  stonesoup/plotter.py
  stonesoup/tests/test_plotter.py
Labels: bug

#741 Correct acronym for (G)OSPA in documentation
  stonesoup/metricgenerator/ospametric.py
Labels: documentation

#379 State time ordered plotter
  docs/examples/TimePlotterExample.py
  stonesoup/plotter.py
Labels: documentation

#734 Add Accumulated State Densities Filter
  LICENSE
  docs/source/stonesoup.predictor.rst
  docs/source/stonesoup.updater.rst
  docs/tutorials/filters/ASDFilter.py
  stonesoup/__init__.py
  stonesoup/plotter.py
  stonesoup/predictor/asd.py
  stonesoup/predictor/kalman.py
  stonesoup/predictor/tests/test_asd.py
  stonesoup/types/prediction.py
  stonesoup/types/state.py
  stonesoup/types/tests/test_prediction.py
  stonesoup/types/tests/test_state.py
  stonesoup/types/tests/test_update.py
  stonesoup/types/update.py
  stonesoup/updater/asd.py
  stonesoup/updater/kalman.py
  stonesoup/updater/tests/test_asd.py
  stonesoup/updater/tests/test_kalman.py
Labels: enhancement
