Repository dstl/Stone-Soup, pull requests merged in 2022-08, with the labels that each got.

#679 Enable use of detections' measurement model in kDTree
  stonesoup/dataassociator/tests/test_tree.py
  stonesoup/dataassociator/tree.py
Labels: enhancement

#686 Add caching of mean and covar on ParticleState
  stonesoup/types/_util.py
  stonesoup/types/state.py
  stonesoup/types/tests/test_state.py
Labels: enhancement

#677 State vectors iterator
  stonesoup/functions/__init__.py
  stonesoup/models/measurement/nonlinear.py
  stonesoup/types/array.py
  stonesoup/types/tests/test_array.py
Labels: breaking

#684 Add Squared Mahalanobis distance and cache covariance matrix inversions
  stonesoup/measures.py
  stonesoup/mixturereducer/gaussianmixture.py
Labels: enhancement

#685 Reset NumPy random state when running Sphinx-Gallery examples
  docs/source/conf.py
  docs/source/doc_extensions.py
  setup.py
Labels: documentation

#667 Add Information Filter Tutorial
  docs/tutorials/12_InformationFilterTutorial.py
  stonesoup/measures.py
  stonesoup/plotter.py
  stonesoup/types/state.py
  stonesoup/types/tests/test_state.py
Labels: documentation

#665 Add optimized sensor management tutorial
  docs/tutorials/sensormanagement/01_SingleSensorManagement.py
  docs/tutorials/sensormanagement/02_MultiSensorManagement.py
  docs/tutorials/sensormanagement/03_OptimisedSensorManagement.py
  stonesoup/sensormanager/optimise.py
Labels: documentation

#692 Fix layout of documentation galleries
  docs/source/_static/css/custom.css
Labels: documentation

#693 Changed ruamel version requirement to 0.16.5
  setup.py
Labels: bug

#650 ADS-B Tracking Demo Fixes
  docs/demos/OpenSky_Demo.py
  docs/demos/OpenSky_Plane_States.csv
  stonesoup/sensor/radar/__init__.py
Labels: documentation

#691 Modify uncertainty reward so sensors measure all tracks together
  stonesoup/sensormanager/reward.py
Labels: enhancement

#699 Add new plotter based on plotly
  .circleci/config.yml
  .readthedocs.yml
  docs/ci-requirements.txt
  docs/source/conf.py
  docs/source/doc_extensions.py
  docs/tutorials/01_KalmanFilterTutorial.py
  docs/tutorials/02_ExtendedKalmanFilterTutorial.py
  docs/tutorials/03_UnscentedKalmanFilterTutorial.py
  docs/tutorials/04_ParticleFilter.py
  docs/tutorials/05_DataAssociation-Clutter.py
  docs/tutorials/06_DataAssociation-MultiTargetTutorial.py
  docs/tutorials/07_PDATutorial.py
  docs/tutorials/08_JPDATutorial.py
  docs/tutorials/09_Initiators_&_Deleters.py
  docs/tutorials/10_Simulation_&_Tracking_Components.py
  docs/tutorials/11_GMPHDTutorial.py
  docs/tutorials/12_InformationFilterTutorial.py
  docs/tutorials/sensormanagement/01_SingleSensorManagement.py
  docs/tutorials/sensormanagement/02_MultiSensorManagement.py
  docs/tutorials/sensormanagement/03_OptimisedSensorManagement.py
  setup.py
  stonesoup/plotter.py
  stonesoup/tests/test_plotter.py
Labels: enhancement

#696 Enable proper shallow copying of state mutable sequences
  stonesoup/sensormanager/reward.py
  stonesoup/types/state.py
  stonesoup/types/tests/test_state.py
  stonesoup/types/track.py
Labels: bug

#700 Fix averaging with StateVectors
  stonesoup/types/array.py
Labels: bug

#701 Tutorial 3 graph legend fix
  docs/tutorials/03_UnscentedKalmanFilterTutorial.py
Labels: documentation

#666 Add example of track-to-track fusion
  docs/examples/Track2Track_Fusion_Example.py
  docs/source/_static/covariance_intersection_formulas.png
Labels: documentation

#703 Add argument for number of points on ellipse polygon with plotly plotter
  stonesoup/plotter.py
Labels: enhancement

#697 Update install instructions to make compatible with zsh
  docs/source/index.rst
Labels: documentation

#705 Update marker styles for tracks in plotters
  stonesoup/plotter.py
Labels: enhancement

#636 Add Nonparametric PDA and gate out non valid measurements
  stonesoup/dataassociator/tests/conftest.py
  stonesoup/gater/tests/test_distance.py
  stonesoup/hypothesiser/probability.py
  stonesoup/hypothesiser/tests/test_composite.py
  stonesoup/hypothesiser/tests/test_probability.py
Labels: breaking

#706 Add the Sliding Innovation Filter
  docs/source/stonesoup.updater.rst
  stonesoup/updater/slidinginnovation.py
  stonesoup/updater/tests/test_sif.py
Labels: enhancement
