Repository dstl/Stone-Soup, pull requests merged in 2022-05, with the labels that each got.

#627 Cast correction term to float in LCCUpdater
  stonesoup/updater/pointprocess.py
Labels: bug

#632 Fix breadcrumbs in documentation
  docs/source/_templates/breadcrumbs.html
Labels: documentation

#628 Prevent track from birth component w/o detection
  docs/tutorials/11_GMPHDTutorial.py
  stonesoup/hypothesiser/gaussianmixture.py
  stonesoup/tracker/pointprocess.py
  stonesoup/tracker/tests/test_pointprocess.py
  stonesoup/types/state.py
Labels: bug

#353 Add diagrams to JPDA tutorial
  docs/source/_static/jpda_diag_1.png
  docs/source/_static/jpda_diag_2.png
  docs/source/_static/jpda_diag_3.png
  docs/tutorials/08_JPDATutorial.py
Labels: documentation

#635 Fix video processing tutorial
  docs/demos/Video_Processing.py
  docs/source/auto_demos/Video_Processing.ipynb
  docs/source/auto_demos/Video_Processing.py.md5
  docs/source/auto_demos/Video_Processing.rst
  docs/source/auto_demos/images/sphx_glr_Video_Processing_001.gif
  docs/source/auto_demos/images/sphx_glr_Video_Processing_002.gif
  docs/source/auto_demos/images/sphx_glr_Video_Processing_003.gif
  docs/source/auto_demos/images/thumb/sphx_glr_Video_Processing_thumb.gif
Labels: documentation

#638 Create MTT 3D Platform example
  docs/examples/MTT_3D_Platform.py
Labels: documentation

#503 Add Sensor Management
  docs/demos/OpenSky_Demo.py
  docs/examples/Creating_Actionable_Sensor.py
  docs/examples/Disjoint_Tracking_Classification.py
  docs/source/_static/actionable_sensor_flow_diagram.png
  docs/source/stonesoup.rst
  docs/source/stonesoup.sensor.action.rst
  docs/source/stonesoup.sensor.rst
  docs/source/stonesoup.sensormanager.rst
  stonesoup/platform/tests/test_platform_base.py
  stonesoup/sensor/action/__init__.py
  stonesoup/sensor/action/dwell_action.py
  stonesoup/sensor/action/tests/__init__.py
  stonesoup/sensor/action/tests/test_dwell_action.py
  stonesoup/sensor/actionable.py
  stonesoup/sensor/passive.py
  stonesoup/sensor/radar/radar.py
  stonesoup/sensor/radar/tests/test_radar.py
  stonesoup/sensor/sensor.py
  stonesoup/sensor/tests/test_actionable.py
  stonesoup/sensor/tests/test_sensor.py
  stonesoup/sensormanager/__init__.py
  stonesoup/sensormanager/base.py
  stonesoup/sensormanager/optimise.py
  stonesoup/sensormanager/reward.py
  stonesoup/sensormanager/tests/__init__.py
  stonesoup/sensormanager/tests/test_sensormanager.py
  stonesoup/simulator/platform.py
  stonesoup/simulator/tests/conftest.py
  stonesoup/tests/test_serialise.py
  stonesoup/types/angle.py
Labels: breaking

#643 Move contract reference from LICENSE file to documentation
  LICENSE
  docs/source/copyright.rst
Labels: documentation

#640 Fix plotting for Multi Sensor Moving Platform Simulator
  docs/examples/Moving_Platform_Simulation.py
Labels: documentation

#637 Add option to specify number of targets in MultiTargetGroundTruthSimulator
  stonesoup/simulator/simple.py
Labels: enhancement

#634 Add options to track to track association algorithm
  stonesoup/dataassociator/tests/test_tracktotrack.py
  stonesoup/dataassociator/tracktotrack.py
  stonesoup/hypothesiser/tests/test_gaussianmixture.py
  stonesoup/measures.py
Labels: breaking

#648 Fix bugs when dealing with Gaussian mixtures
  stonesoup/mixturereducer/gaussianmixture.py
  stonesoup/updater/pointprocess.py
Labels: bug
