Repository dstl/Stone-Soup, pull requests merged in 2023-08, with the labels that each got.

#832 Fix recursion error when printing objects
  stonesoup/base.py
Labels: bug

#833 Set minimum version for sphinx_rtd_theme
  setup.cfg
Labels: documentation

#825 Add a SingleTargetMixtureTracker
  stonesoup/tracker/simple.py
  stonesoup/tracker/tests/test_simple.py
Labels: enhancement

#664 One to one Assignment for Association
  stonesoup/dataassociator/_assignment.py
  stonesoup/dataassociator/tests/test_assignment.py
  stonesoup/dataassociator/tests/test_tracktotrack.py
  stonesoup/dataassociator/tracktotrack.py
  stonesoup/metricgenerator/basicmetrics.py
  stonesoup/metricgenerator/tests/test_basicmetrics.py
  stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
  stonesoup/metricgenerator/tracktotruthmetrics.py
  stonesoup/types/association.py
  stonesoup/types/interval.py
  stonesoup/types/tests/test_association.py
  stonesoup/types/tests/test_interval.py
  stonesoup/types/tests/test_metric.py
  stonesoup/types/tests/test_time.py
  stonesoup/types/time.py
Labels: enhancement

#839 Fix bug in BaseRepr.whitespace_remove() walrus expression
  stonesoup/base.py
Labels: bug
