Repository dstl/Stone-Soup, pull requests merged in 2023-01, with the labels that each got.

#753 Simple update of SIAP metric reference in Metrics example.
  docs/examples/Metrics.py
Labels: documentation

#751 TimeBasedPlotter default timestamps and Notebook animation docs
  .gitignore
  docs/examples/TimePlotterExample.py
  stonesoup/plotter.py
Labels: enhancement

#759 Ensure ranges are floats in optimise sensor manager
  stonesoup/sensormanager/optimise.py
Labels: bug

#758 Fix covar for ConstantNthDerivative model
  stonesoup/models/transition/linear.py
Labels: bug

#745 Add Python 3.11 to CI builds
  .circleci/config.yml
  .codecov.yml
  .github/workflows/docs-link.yml
  .readthedocs.yml
Labels: tests

#763 Fix Angle.__abs__ such that it always returns a positive value
  stonesoup/types/angle.py
  stonesoup/types/tests/test_angle.py
Labels: bug

#766 Fix test comparing platform angles close to ±π
  stonesoup/platform/tests/test_platform_base.py
Labels: tests
