Repository dstl/Stone-Soup, pull requests merged in 2023-05, with the labels that each got.

#804 Change track stitching example initiator
  docs/examples/Track_Stitcher_Example.py
Labels: documentation

#789 Add animated variation of plotterly
  docs/source/_static/sphinx_gallery/Tutorial_1.png
  docs/source/_static/sphinx_gallery/Tutorial_10.png
  docs/source/_static/sphinx_gallery/Tutorial_2.png
  docs/source/_static/sphinx_gallery/Tutorial_3.png
  docs/source/_static/sphinx_gallery/Tutorial_4.png
  docs/source/_static/sphinx_gallery/Tutorial_5.png
  docs/source/_static/sphinx_gallery/Tutorial_6.png
  docs/source/_static/sphinx_gallery/Tutorial_7.png
  docs/source/_static/sphinx_gallery/Tutorial_8.png
  docs/source/_static/sphinx_gallery/Tutorial_9.png
  docs/tutorials/01_KalmanFilterTutorial.py
  docs/tutorials/02_ExtendedKalmanFilterTutorial.py
  docs/tutorials/03_UnscentedKalmanFilterTutorial.py
  docs/tutorials/04_ParticleFilter.py
  docs/tutorials/05_DataAssociation-Clutter.py
  docs/tutorials/06_DataAssociation-MultiTargetTutorial.py
  docs/tutorials/07_PDATutorial.py
  docs/tutorials/08_JPDATutorial.py
  docs/tutorials/09_Initiators_&_Deleters.py
  docs/tutorials/10_Simulation_&_Tracking_Components.py
  docs/tutorials/sensormanagement/01_SingleSensorManagement.py
  docs/tutorials/sensormanagement/02_MultiSensorManagement.py
  docs/tutorials/sensormanagement/03_OptimisedSensorManagement.py
  stonesoup/plotter.py
  stonesoup/tests/test_plotter.py
Labels: enhancement

#771 add k-d tree tutorial and update tree sub-module
  docs/source/_static/kd_tree_fig_1.png
  docs/source/_static/kd_tree_fig_2.png
  docs/source/_static/kd_tree_fig_3.png
  docs/tutorials/dataassociation/KDTree_Tutorial.py
  docs/tutorials/dataassociation/README.rst
  stonesoup/dataassociator/tree.py
Labels: enhancement

#807 Fix issue with kD-tree example not building
  docs/tutorials/dataassociation/KDTree_Tutorial.py
Labels: documentation

#806 Enable Forward Declaration of Type Hints for Properties
  stonesoup/base.py
  stonesoup/tests/test_declarative.py
Labels: bug

#808 Drop Python 3.7 support, and remove references to beta
  .circleci/config.yml
  README.md
  docs/source/index.rst
  setup.cfg
  stonesoup/_util.py
  stonesoup/base.py
Labels: breaking
