Repository dstl/Stone-Soup, pull requests merged in 2023-03, with the labels that each got.

#775 Cast noise_covar value to a CovarianceMatrix when initialising a MeasurementModel
  docs/examples/Creating_Actionable_Sensor.py
  docs/examples/range_range_rate_binning.py
  docs/tutorials/filters/ASDFilter.py
  stonesoup/models/measurement/linear.py
  stonesoup/models/measurement/nonlinear.py
  stonesoup/models/measurement/tests/test_combined.py
  stonesoup/models/measurement/tests/test_models.py
  stonesoup/updater/tests/test_alphabeta.py
Labels: bug

#777 Use temporary file for FITS Reader tests
  stonesoup/reader/tests/test_astronomical.py
Labels: tests

#707 Added an example within the documentation for custom readers supporting pandas DataFrames.
  docs/examples/Custom_Pandas_Dataloader.py
  setup.cfg
  stonesoup/reader/pandas_reader.py
  stonesoup/reader/tests/test_pandas_reader.py
Labels: enhancement

#778 Created RadarBearing and RadarRotatingBearing Sensors
  stonesoup/sensor/radar/radar.py
  stonesoup/sensor/radar/tests/test_radar.py
Labels: enhancement
