Repository dstl/Stone-Soup, pull requests merged in 2024-10, with the labels that each got.

#1084 Sensor performance improvement
  stonesoup/functions/__init__.py
  stonesoup/sensor/passive.py
  stonesoup/sensor/radar/radar.py
  stonesoup/sensor/radar/tests/test_radar.py
  stonesoup/sensor/sensor.py
Labels: breaking

#1064 Don't set global random seed in tests
  stonesoup/functions/__init__.py
  stonesoup/metricgenerator/tests/test_ospametric.py
  stonesoup/models/measurement/gas.py
  stonesoup/models/measurement/tests/test_gas.py
  stonesoup/predictor/particle.py
  stonesoup/predictor/tests/test_particle.py
  stonesoup/sampler/detection.py
  stonesoup/sampler/particle.py
  stonesoup/sensor/tests/test_gas.py
  stonesoup/tests/test_kernel.py
  stonesoup/tests/test_stitcher.py
  stonesoup/types/tests/test_prediction.py
  stonesoup/types/tests/test_update.py
Labels: tests

#1091 Add init file for proposal class
  stonesoup/proposal/__init__.py
Labels: bug

#1095 Handle MFA infeasible primal problem
  stonesoup/dataassociator/mfa/_step.py
Labels: bug

#1097 Vectorise logpdf mod_angle calculations in angle based models
  stonesoup/functions/__init__.py
  stonesoup/models/measurement/nonlinear.py
  stonesoup/models/measurement/tests/test_models.py
Labels: breaking
