Repository dstl/Stone-Soup, pull requests merged in 2024-01, with the labels that each got.

#916 Adapted the square root components
  stonesoup/predictor/kalman.py
  stonesoup/updater/kalman.py
Labels: enhancement

#917 Fix bug in GridActionGenerator
  stonesoup/movable/action/move_position_action.py
  stonesoup/movable/action/tests/test_move_position_action.py
  stonesoup/movable/actionable_movable.py
Labels: bug

#918 Shorten sensor management tutorials' simulation length
  docs/tutorials/sensormanagement/01_SingleSensorManagement.py
  docs/tutorials/sensormanagement/02_MultiSensorManagement.py
  docs/tutorials/sensormanagement/03_OptimisedSensorManagement.py
Labels: enhancement

#919 Adding setting title functionality to AnimationPlotter
  stonesoup/plotter.py
  stonesoup/tests/test_plotter.py
Labels: enhancement

#925 Add support for Python 3.12
  .circleci/config.yml
  .git_archival.txt
  .readthedocs.yml
  MANIFEST.in
  docs/source/conf.py
  pyproject.toml
  setup.cfg
  stonesoup/__init__.py
  stonesoup/base.py
  stonesoup/dataassociator/tests/test_tracktotrack.py
  stonesoup/feeder/tests/conftest.py
  stonesoup/functions/tests/test_functions.py
  stonesoup/initiator/tests/test_simple.py
  stonesoup/metricgenerator/tests/test_plotter.py
  stonesoup/plugins.py
  stonesoup/predictor/tests/test_information.py
  stonesoup/sensormanager/reward.py
  stonesoup/sensormanager/tests/test_sensormanager.py
  stonesoup/serialise.py
  stonesoup/simulator/tests/test_detections.py
  stonesoup/tests/test_declarative.py
  stonesoup/tests/test_stitcher.py
  stonesoup/types/array.py
  stonesoup/types/association.py
  stonesoup/types/orbitalstate.py
  stonesoup/types/tests/test_array.py
  stonesoup/types/tests/test_orbital.py
  stonesoup/types/tests/test_prediction.py
  stonesoup/types/tests/test_state.py
  stonesoup/updater/tests/test_alphabeta.py
  stonesoup/updater/tests/test_asd.py
  stonesoup/updater/tests/test_chernoff.py
  stonesoup/updater/tests/test_information.py
  stonesoup/updater/tests/test_kalman.py
  stonesoup/updater/tests/test_pointprocess.py
  stonesoup/updater/tests/test_sif.py
Labels: enhancement

#928 Make Metrics Example Flake8 Compliant
  docs/examples/Metrics.py
Labels: documentation

#927 Simplify (or at least make more standard) control models
  stonesoup/models/control/base.py
  stonesoup/models/control/linear.py
  stonesoup/models/control/tests/__init__.py
  stonesoup/models/control/tests/test_control.py
  stonesoup/predictor/information.py
  stonesoup/predictor/kalman.py
Labels: enhancement
