Repository dstl/Stone-Soup, pull requests merged in 2024-07, with the labels that each got.

#1056 Only use one track state per timestamp in (G)OSPA metric
  stonesoup/metricgenerator/ospametric.py
Labels: bug

#1017 CLEAR MOT Associator
  docs/source/stonesoup.dataassociator.rst
  stonesoup/dataassociator/clearmot.py
  stonesoup/dataassociator/tests/test_clearmot.py
  stonesoup/dataassociator/tests/test_tracktotrack.py
  stonesoup/dataassociator/tracktotrack.py
Labels: enhancement

#1065 Fix plotting tests due to typo in warning message
  stonesoup/tests/test_plotter.py
Labels: tests

#1066 Fix UncertaintyReward bug and improve ExpectedKLDivergence
  stonesoup/sensormanager/reward.py
Labels: bug

#1063 Handle distance of 0 correctly in TrackToTruth associator
  stonesoup/dataassociator/tracktotrack.py
Labels: bug

#1061 Update AKKF tutorial
  docs/source/_static/AKKF_flow_diagram.png
  docs/source/_static/KME.png
  docs/tutorials/filters/AKKF.py
Labels: documentation
