Repository dstl/Stone-Soup, pull requests merged in 2024-02, with the labels that each got.

#955 Avoid test collection failure with optional dependency astropy
  stonesoup/reader/tests/test_astronomical.py
  stonesoup/types/tests/test_orbital.py
Labels: tests

#957 Add pyehm plugin as optional tests
  .circleci/config.yml
  stonesoup/dataassociator/tests/test_probability.py
  stonesoup/plugins.py
Labels: tests

#943 Sensor management with actionable movables
  docs/examples/Creating_Actionable_Sensor.py
  docs/source/stonesoup.movable.rst
  docs/source/stonesoup.sensor.action.rst
  docs/source/stonesoup.sensor.rst
  docs/source/stonesoup.sensormanager.rst
  stonesoup/movable/action/move_position_action.py
  stonesoup/movable/action/tests/test_move_position_action.py
  stonesoup/movable/grid.py
  stonesoup/movable/movable.py
  stonesoup/sensor/action/__init__.py
  stonesoup/sensor/action/dwell_action.py
  stonesoup/sensor/action/tests/test_dwell_action.py
  stonesoup/sensor/radar/radar.py
  stonesoup/sensor/sensor.py
  stonesoup/sensor/tests/test_actionable.py
  stonesoup/sensormanager/action.py
  stonesoup/sensormanager/base.py
  stonesoup/sensormanager/reward.py
  stonesoup/sensormanager/tests/test_sensormanager.py
Labels: breaking

#945 Fix incorrect transition model being used in Kalman Smoothers
  stonesoup/predictor/kalman.py
  stonesoup/smoother/kalman.py
  stonesoup/updater/tests/test_iterated.py
Labels: bug

#959 Fix unused variable in Comparing Multiple Trackers example
  docs/examples/Multi_Tracker_Example.py
Labels: documentation

#963 Fix calculation of cross-covariance in unscented_transform
  stonesoup/functions/__init__.py
Labels: bug

#912 Fixing bug which causes multiplication by Probability to return a Probability
  stonesoup/hypothesiser/probability.py
  stonesoup/types/numeric.py
  stonesoup/types/tests/test_numeric.py
Labels: bug
