Repository dstl/Stone-Soup, pull requests merged in 2024-06, with the labels that each got.

#1024 Fix Inverse Function in CartesianToElevationBearingRangeRate
  stonesoup/models/measurement/nonlinear.py
  stonesoup/models/measurement/tests/test_models.py
Labels: bug

#1036 Fix incorrect generator kwargs with grid moveables
  stonesoup/movable/grid.py
Labels: bug

#1037 Fix CartesianToElevationBearingRangeRate inverse velocity and clutter plotting
  stonesoup/models/measurement/nonlinear.py
  stonesoup/plotter.py
Labels: bug

#1042 Fix GaussianMixtureInitiator to use a MultiMeasurementInitiator
  stonesoup/initiator/simple.py
  stonesoup/initiator/tests/test_simple.py
Labels: bug

#1023 Monte Carlo Tree Search Sensor Manager and Autonomous STE Examples
  docs/examples/sensormanagement/Autonomous_Source_Term_Estimation.py
  docs/examples/sensormanagement/Monte_Carlo_Tree_Search_for_Autonomous_Source_Term_Estimation.py
  docs/source/stonesoup.sensormanager.rst
  stonesoup/models/measurement/gas.py
  stonesoup/sensormanager/reward.py
  stonesoup/sensormanager/tests/test_sensormanager.py
  stonesoup/sensormanager/tree_search.py
  stonesoup/types/state.py
Labels: enhancement

#1045 Minor deprecation fixes
  docs/examples/readers/Custom_Pandas_Dataloader.py
  stonesoup/measures/state.py
  stonesoup/movable/movable.py
  stonesoup/reader/aishub.py
  stonesoup/reader/generic.py
  stonesoup/reader/hdf5.py
  stonesoup/reader/kafka.py
  stonesoup/reader/opensky.py
  stonesoup/reader/pandas_reader.py
  stonesoup/tests/test_stitcher.py
  stonesoup/types/array.py
Labels: bug

#1049 Fix repr on Base class
  stonesoup/base.py
Labels: bug

#1044 Set weakref to particle parent parent, rather than None
  stonesoup/types/particle.py
  stonesoup/types/state.py
  stonesoup/types/tests/test_particle.py
  stonesoup/types/tests/test_state.py
Labels: enhancement

#1051 Add download link to OpenSky Demo CSV and full links to icons
  docs/demos/OpenSky_Demo.py
Labels: documentation
