Repository dstl/Stone-Soup, pull requests merged in 2025-02, with the labels that each got.

#1113 Make track uncertainty alpha an optional keyword argument
  stonesoup/plotter.py
Labels: enhancement

#1117 Fix flaky StochasticIntegrationUpdater test
  stonesoup/updater/tests/test_kalman.py
Labels: tests

#1123 Vectorise the unscented transform
  stonesoup/functions/__init__.py
  stonesoup/functions/tests/test_functions.py
  stonesoup/predictor/kalman.py
Labels: breaking

#1122 Kalman Smoother check GaussianState and Prediction/Update separately
  stonesoup/smoother/kalman.py
Labels: bug

#1124 Use full test template for Python 3.13 CircleCI config
  .circleci/config.yml
Labels: tests
