Repository dstl/Stone-Soup, pull requests merged in 2025-03, with the labels that each got.

#1134 Allow setting of gm_method at instance level for PDAUpdater
  stonesoup/updater/probability.py
  stonesoup/updater/tests/test_probability.py
Labels: bug

#1131 Rename PriorAsProposal to DynamicsProposal, and KFasProposal to KalmanProposal
  stonesoup/predictor/particle.py
  stonesoup/proposal/simple.py
  stonesoup/proposal/tests/test_simple.py
Labels: breaking

#1132 Add docs for tracker update_tracker method
  docs/source/stonesoup.tracker.rst
  stonesoup/tracker/base.py
Labels: documentation

#1141 Fix flaky ensemble updater tests
  stonesoup/updater/tests/test_ensemble.py
Labels: tests

#1147 Add multi data feeders with queues
  stonesoup/feeder/multi.py
  stonesoup/feeder/tests/test_multi.py
Labels: enhancement

#1148 Add SinglePointMeasurementInitiator
  stonesoup/initiator/simple.py
  stonesoup/initiator/tests/test_simple.py
Labels: enhancement

#1149 Update Copyright Year for 2025
  LICENSE
  docs/source/conf.py
  stonesoup/__init__.py
Labels: documentation
